language: php
php:
  - 5.5
  - 5.4
  - 5.3
script: (cd tests; php run_tests.php)
services: mongodb
before_script:
  - mysql -e 'create database myapp_test'
  - mysql myapp_test < tests/test.sql
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
notifications:
  irc:
    channels:
      - chat.freenode.net#atk4
    on_success: always
    on_failure: always
  email: false
  flowdock:
    - secure: Iyvr9KzrWbZ4CPoJA23+WzPrCLYo1QDll0Ka69qkma9E1YsoC/ysmdjFZvQBGM2odVk7AShfGiSWo3ndng+BbOIA8QsGfGQdydoLh4El1JBKm4oQbinDF9wbRHhNk4vJOkqIObUZcDZbQcO9Vm65jQQkyxmJ5RlbrpwnP4UsjXc=
